### ISSUE TITLE
add list of ableist language?

### ISSUE THREAD

**Issue by coleww** [jimkang/iscool#10]
i noticed one of my bots tweeted "moron" and then godtribs replied to it :(

I'm not sure if this is something you want in the scope of iscool, but i saw sui recommend this in the botally chat http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

**Comment by jimkang** [comment]
Doh, sorry that happened. From my perspective, some of those are slam-dunk always-block words, like "spaz" and "retard," but others seem like they may be too broad (like "dumb" or "nuts") for default, all-context block use. I'll probably add at least those two.

However, in your wrapper (and you may already know this), you can add whatever you want to the customBlacklist to get them classified as not-cool:

```var isCool = createIsCool({
  customBlacklist: [
    'hastur',
    'voldemort'
  ]
}```

I use that when I don't think something is general enough.

**Comment by coleww** [comment]
nice, yeah i want to make TIPOTS start filtering for other things, like word sequences that are ok on their own but probably not ok for a bot to talk about i.e, "electric chair"
