### ISSUE TITLE
Usage example contains additonal ")"

### ISSUE THREAD

**Issue by m-r-m-s** [jimkang/iscool#12]
@jimkang I was testing module and I believe there may be an additional `)` in the example below? https://github.com/jimkang/iscool#usage 
`isCool('hastur')); `
```
var isCool = createIsCool({
  customBlacklist: [
    'hastur',
    'voldemort'
  ],
  logger: console
});

isCool('hastur')); 
// false
// Uncool word: hastur
```

**Comment by jimkang** [comment]
@m-r-m-s Thanks for catching that! Fixed.
