### ISSUE TITLE
if you forget to makeIsCool, bad things occur

### ISSUE THREAD

**Issue by coleww** [jimkang/iscool#6]
hello! 

I noticed that if someone accidentally does something like this:

```
var iscool = require('iscool')
if (iscool(some_horrible_string)){
...    
}
```

then since the iscool constructor returns a function, it will always return true.
 
Could it throw an error if the constructor function is passed a string? I'd be happy to make such a PR :+1: :clap:

**Comment by jimkang** [comment]
Oh, man, right – it doesn't quite work like a lot of singleton modules, which can lead to this! Sure, if you have time go ahead and PR. Otherwise, I can do it tonight.

**Comment by coleww** [comment]
ISSUE: CRUSHED.

**Comment by jimkang** [comment]
:fist:
