### ISSUE TITLE
language of "Blacklist"

### ISSUE THREAD

**Issue by suisea** [jimkang/iscool#9]
hi, after consideration i'm starting to weed out the word "blacklist" (logic here: https://medium.com/@beaugunderson/things-i-ve-stopped-saying-fa7dea0bf317#.3fbeyqcmf ). perhaps i'd consider renaming it in the code "filter" or "exclude" or whatever? :O

**Comment by jimkang** [comment]
Thanks! That's something I'll definitely keep in mind the next time I name this kind of property, but I think I'm going to leave this one, as it would be a breaking change that would force other programs using this module to all update that property name.
